name = input('Enter your Name:')
addrs1 = input('Enter Address line 1')
addrs2 = input('Enter Address line 2')
addrs3 = input('Enter Address line 3')
city = input('Enter city Name:')
state = input('Enter State Name:')
pin = input('Enter your Pin code :')
print(name)
print('Address:')
print(addrs1)
print(addrs2)
print(addrs3)